version: '3.3'
networks:
  elk:

volumes:
  elasticsearch:
    driver: local

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    networks:
      elk: null
    ports:
    - 9200:9200
    restart: unless-stopped
    volumes:
    - elasticsearch:/usr/share/elasticsearch/data:rw
    - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.4.2
    depends_on:
    - elasticsearch
    networks:
      elk: null
    ports:
    - 5044:5044
    - 9600:9600 #api port https://www.elastic.co/guide/en/logstash/current/logging.html#_logging_apis
    restart: unless-stopped
    volumes:
    - ./logstash/pipeline/:/usr/share/logstash/pipeline:ro
    - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml

  kibana:
    depends_on:
    - elasticsearch
    environment:
      ELASTICSEARCH_PASSWORD: changeme
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
    image: elasticsearch-davidb:latest
    volumes:
        - ./kibana/plugins/logtrail.json:/usr/share/kibana/plugins/logtrail/logtrail.json
        - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      elk: null
    ports:
    - 5601:5601
    restart: unless-stopped
