## Default Logstash configuration from logstash-docker.
## from https://github.com/elastic/logstash-docker/blob/master/build/logstash/config/logstash-oss.yml
#
http.host: "0.0.0.0"
#path.config: /usr/share/logstash/pipeline #https://github.com/elastic/logstash/issues/8420
log.level: info #https://www.elastic.co/guide/en/logstash/current/logstash-settings-file.html
#xpack.monitoring.elasticsearch.url: http://elasticsearch:9200